# 1. Block សម្រាប់ Frontend (i-knet.com)
server {
    listen 80;
    server_name i-knet.com;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.i-knet.com; img-src * data: blob:;" always;
    }
}

# 2. Block សម្រាប់ Backend (api.i-knet.com)
server {
    listen 80;
    server_name api.i-knet.com;

    location /api/ {
        # កាត់ /api/ ចេញ មុនពេលផ្ញើទៅ Java
        rewrite ^/api/(.*)$ /$1 break;

        # ផ្ញើទៅ Java Backend (ត្រូវតែជា Port 8080)
        proxy_pass http://127.0.0.1:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}